package com.hospital.grievance.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    COMPLAINT_SUBMITTED,
    COMPLAINT_ASSIGNED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    INVESTIGATION_STARTED,
    INVESTIGATION_UPDATED,
    INVESTIGATION_COMPLETED,
    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    USER_ENABLED,
    QR_GENERATED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    LOCATION_CREATED,
    LOCATION_UPDATED,
    DATA_EXPORTED
}
